mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ratesmash/', include('ratesmash.urls')),
]

ratesmash/urls.py
from django.urls import path

from . import views

app_name = 'ratesmash'
urlpatterns = [
    path('', views.index, name='index'),
    path('create_room/', views.create_room, name='create_room'),
    path('room_detail/<int:room_id>/', views.room_detail, name='room_detail'),
    path('join_room/<int:room_id>/', views.join_room, name='join_room'),
    path('delete_room/<int:room_id>/', views.delete_room, name='delete_room'),
    path('send_result/<int:room_id>/', views.send_result, name='send_result'),
    path('all_players/', views.all_players, name='all_players'),
    path('player_detail/<int:player_id>/', views.player_detail, name='player_detail'),
    path('howtoplay/', views.howtoplay, name='howtoplay'),
    path('error_message/', views.error_message, name='error_message'),
    path('ranking/', views.ranking, name='ranking'),
]

ratesmash/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Player(models.Model):
    user = models.OneToOneField(User,
                             on_delete=models.CASCADE,
                             verbose_name='handle_name')
    MAIN_CHARACTER = (
            ('LU', 'luigi'),
            ('MA', 'mario'),
            ('DK', 'donkey_kong'),
            ('LI', 'link'),
            ('SA', 'samus'),
            ('CF', 'captain_falcon'),
            ('NE', 'ness'),
            ('YO', 'yoshi'),
            ('KI', 'kirby'),
            ('FO', 'fox'),
            ('PI', 'pikachu'),
            ('PU', 'purin'),
            )
    main = models.CharField(max_length=2, choices=MAIN_CHARACTER)
    rate = models.IntegerField(default=1500)
    playable = models.BooleanField(default=True) # Falseの場合試合中or処理中
    
    def __str__(self):
        return self.user.username
    
    
class Room(models.Model):
    owner = models.ForeignKey(Player,
                             on_delete=models.CASCADE,
                             related_name='owner')
    participant = models.ForeignKey(Player,
                                    on_delete=models.CASCADE,
                                    null=True,
                                    blank=True,
                                    related_name='participant')
    STATE_SET = (
            ('w', 'wait'),
            ('d', 'during'),
            ('f', 'finish'),
            ('p', 'processing'))
    state = models.CharField(max_length=1, choices=STATE_SET, default='w')
    comment = models.CharField(max_length=20, blank=True)
    pub_date = models.DateTimeField(default=timezone.now)
    SERVER_LIST = (
            ('tetsu', 'tetsu_server'),
            ('kaillera', 'kaillera_server'),
            ('exo', 'exo_server'),
            ('heijokyo', 'heijokyo'),
            )
    server = models.CharField(max_length=10, choices=SERVER_LIST)
    CF_LIST = (
            ('1', '1'),
            ('2', '2'),
            )
    cf = models.CharField(max_length=1, choices=CF_LIST)
    mode = models.BooleanField()
    rate_o = models.IntegerField(blank=True, null=True)
    rate_p = models.IntegerField(blank=True, null=True)
    
    def __str__(self):
        return str(self.id)
    
    
class Result(models.Model):
    player1 = models.ForeignKey(Player,
                                on_delete=models.CASCADE,
                                related_name='player1')
    player2 = models.ForeignKey(Player,
                                on_delete=models.CASCADE,
                                related_name='player2')
    winloss = models.BooleanField()
    room = models.ForeignKey(Room,
                             on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.room.id)

ratesmash/forms.py
from django import forms


class RoomForm(forms.Form):
    SERVER_LIST = (
            ('tetsu', 'tetsu_server'),
            ('kaillera', 'kaillera_server'),
            ('exo', 'exo_server'),
            ('heijokyo', 'heijokyo'),
            )
    server = forms.ChoiceField(choices=SERVER_LIST)
    CF_LIST = (
            ('1', '1'),
            ('2', '2'),
            )
    cf = forms.ChoiceField(choices=CF_LIST)
    MASK_MODE = (
                (False, '公開'),
                (True, '匿名')
                )
    mode = forms.ChoiceField(choices=MASK_MODE)
    comment = forms.CharField(max_length=20, required=False)
    
    
class ResultForm(forms.Form):
    WINLOSS = (
            (True, 'win'),
            (False, 'loss')
            )
    result = forms.ChoiceField(choices=WINLOSS, widget=forms.RadioSelect())

ratesmash/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required

from .models import Player, Room, Result
from .forms import RoomForm, ResultForm


def index(request):
    waiting_room = Room.objects.all().filter(state='w').order_by('pk').reverse()
    active_room = Room.objects.all().filter(state='d').order_by('pk').reverse()
    processing_room = Room.objects.all().filter(state='p').order_by('pk').reverse()
    finished_room = Room.objects.all().filter(state='f').order_by('pk').reverse()
    context = {
            'title':'rate smash',
            'subtitle':'',
            'waiting_room':waiting_room,
            'active_room':active_room,
            'processing_room':processing_room,
            'finished_room':finished_room,
            }
    return render(request, 'ratesmash/index.html', context)

@login_required(login_url='/admin/login/')
def create_room(request):
    player = Player.objects.get(user=request.user)
    if request.method == 'POST':
        form = RoomForm(request.POST)
        
        if form.is_valid():
            room = Room(
                    owner=player,
                    state='w',
                    comment=request.POST['comment'],
                    server=request.POST['server'],
                    cf=request.POST['cf'],
                    mode=request.POST['mode'],
                    rate_o = player.rate
                    )
            room.save()
            player.playable = False
            player.save()
            return HttpResponseRedirect('/ratesmash/')        
    else:
        if not player.playable:
            return HttpResponseRedirect('/ratesmash/error_message/')
        form = RoomForm()
    context = {
            'title':'rate smash',
            'subtitle':'create room',
            'message':'fill in the blanks',
            'form':form
            }        
    return render(request, 'ratesmash/create_room.html', context)

def room_detail(request, room_id):
    room = Room.objects.get(id=room_id)
    # ログインしているかどうか
    if request.user.is_authenticated: # ログインしている場合
        player = Player.objects.get(user=request.user)
        if room.owner == player or room.participant == player:
            if room.state == 'd' or room.state == 'p':
                return HttpResponseRedirect('/ratesmash/send_result/{}/'.format(room_id))
            elif room.state == 'w' and room.owner == player:
                context = context = {
                'title':'rate smash',
                'subtitle':'room detail',
                'room':room,
                'player':player,
                }
                return render(request, 'ratesmash/room_detail.html', context)
            else:
                pass
        else:
            pass
    else: # ログインしていない場合
        pass
    
    if room.state == 'w' or room.state == 'd' or room.state == 'p':
        context = context = {
                'title':'rate smash',
                'subtitle':'room detail',
                'room':room,
                }
    else:
        results = Result.objects.filter(room=room)
        context = {
                'title':'rate smash',
                'subtitle':'room detail',
                'room':room,
                'resulto':results.get(player1=room.owner).winloss,
                'resultp':results.get(player1=room.participant).winloss,
                }
    return render(request, 'ratesmash/room_detail.html', context)

@login_required(login_url='/admin/login/')
def join_room(request, room_id):
    room = Room.objects.get(id=room_id)
    player = Player.objects.get(user=request.user)
    if not player.playable:
        return HttpResponseRedirect('/ratesmash/error_message/')
    else:
        room.participant = player
        room.state = 'd'
        room.rate_p = player.rate
        room.save()
        player.playable = False
        player.save()
        return HttpResponseRedirect('/ratesmash/send_result/{}/'.format(room_id))
    
@login_required(login_url='/admin/login/')
def delete_room(request, room_id):
    room = Room.objects.get(id=room_id)
    player = Player.objects.get(user=request.user)
    if player == room.owner:
        room.owner.playable = True
        room.owner.save()
        if room.participant == None:
            pass
        else:
            room.participant.playable = True
            room.participant.save()
        room.delete()        
        return HttpResponseRedirect('/ratesmash/')
    else:
        return HttpResponseRedirect('/ratesmash/')

@login_required(login_url='/admin/login/')
def send_result(request, room_id):
    if request.method == 'POST':
        form = ResultForm(request.POST)
        
        if form.is_valid():
            room = Room.objects.get(id=room_id)
            player = Player.objects.get(user=request.user)
            results = Result.objects.filter(room=room).filter(player1=player)
            if player == room.owner:
                if len(results) == 0:
                    result = Result(
                            player1=player,
                            player2=room.participant,
                            winloss=request.POST['result'],
                            room=room,
                            )
                    result.save()
                else:
                    result = Result.objects.filter(room=room).get(player1=player)
                    result.winloss = request.POST['result']
                    result.save()
            elif player == room.participant:
                if len(results) == 0:
                    result = Result(
                            player1=player,
                            player2=room.owner,
                            winloss=request.POST['result'],
                            room=room,
                            )
                    result.save()
                else:
                    result = Result.objects.filter(room=room).get(player1=player)
                    result.winloss = request.POST['result']
                    result.save()
            else:
                pass
            process_rate(room_id)
            return HttpResponseRedirect('/ratesmash/')
    else:
        form = ResultForm()
    room = Room.objects.get(id=room_id)
    context = {
            'title':'rate smash',
            'subtitle':'send result',
            'message':'choose win/loss',
            'room':room,
            'form':form
            }
    return render(request, 'ratesmash/send_result.html', context) 

def all_players(request):
    players = Player.objects.all()
    context = {
            'title':'rate smash',
            'subtitle':'all players',
            'players':players,
            }
    return render(request, 'ratesmash/all_players.html', context)

def player_detail(request, player_id):
    player = Player.objects.get(id=player_id)
    results = Result.objects.filter(player1=player).order_by('-room__pub_date')
    context = {
            'title':'rate smash',
            'subtitle':'player detail',
            'player':player,
            'results':results,
            }
    return render(request, 'ratesmash/player_detail.html', context)

def ranking(request):
    players = Player.objects.all().order_by('rate').reverse()
    context = {
            'title':'rate smash',
            'subtitle':'ranking',
            'players':players,
            }
    return render(request, 'ratesmash/ranking.html', context)

def howtoplay(request):
    context = dict()
    return render(request, 'ratesmash/howtoplay.html', context)

def error_message(request):
    context = {
            'title':'rate smash',
            'subtitle':'error message',
            }
    return render(request, 'ratesmash/error_message.html', context)

"""
general function
"""
def process_rate(room_id):
    room = Room.objects.get(id=room_id)
    results = Result.objects.filter(room=room)
    if len(results) == 0:
        pass
    elif len(results) == 1:
        room.state = 'p'
        room.save()
    else:
        player1 = room.owner
        player2 = room.participant
        winloss1 = results.get(player1=player1).winloss
        winloss2 = results.get(player1=player2).winloss
        if winloss1 == winloss2:
            room.state = 'p'
            room.save()
        else:
            rate1 = player1.rate
            rate2 = player2.rate
            room.state = 'f'
            room.save()
            if abs(rate1 - rate2) >= 400:
                if rate1 > rate2:
                    if winloss1 == True:
                        player1.playable = True
                        player1.save()
                        player2.playable = True
                        player2.save()
                    else:
                        player1.rate -= int(16 + (rate1 - rate2) * 0.04)
                        player1.playable = True
                        player1.save()
                        player2.rate += int(16 + (rate1 - rate2) * 0.04)
                        player2.playable = True
                        player2.save()
                else:
                    if winloss2 == True:
                        player1.playable = True
                        player1.save()
                        player2.playable = True
                        player2.save()
                    else:
                        player1.rate += int(16 + (rate2 - rate1) * 0.04)
                        player1.playable = True
                        player1.save()
                        player2.rate -= int(16 + (rate2 - rate1) * 0.04)
                        player2.playable = True
                        player2.save()
            else:
                if winloss1 == True:
                    player1.rate += int(16 + (rate2 - rate1) * 0.04)
                    player1.playable = True
                    player1.save()
                    player2.rate -= int(16 + (rate2 - rate1) * 0.04)
                    player2.playable = True

ratesmash/templates/ratesmash/all_players.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" 
    href="{% static 'ratesmash/style.css' %}" />
</head>
<body class="allplayer">
    <div class="allplayer-body">
        <header>
            <h1><a href="{% url 'ratesmash:index' %}">{{ title }}</a></h1>
            <p>
            <strong>beginner python</strong> による勉強用サイトです！<br>
            初めての方はhow to playを一読してからご利用ください！
            </p>
            <h2>{{ subtitle }}</h2>
        </header>
        
        <hr>
        
        <nav class="menu">
            <ul class="menu-bar">
                <li class="menu-item"><a href="{% url 'ratesmash:create_room' %}">部屋をつくる</a></li>
                <li class="menu-item"><a href="{% url 'ratesmash:all_players' %}">プレイヤー一覧</a></li>
                <li class="menu-item"><a href="{% url 'ratesmash:ranking' %}">ランキング</a></li>
                <li class="menu-item"><a href="{% url 'ratesmash:howtoplay' %}">ヘルプ</a></li>
            </ul>
        </nav>
        
        <hr>
        
        <div class="main-content">
        
            <div class="board">
                <p>プレイヤー一覧</p>
                <hr>
                <p>参加者はここに載ってますよ。</p>
            </div>
    
            
            <div class="player-list">
                <table>
                    <tr>
                        <th>ハンドルネーム</th>
                        <th>キャラクター</th>
                        <th>レート</th>
                    </tr>
                {% for player in players %}
                    <tr>
                        <td><a href="{% url 'ratesmash:player_detail' player.id %}">{{ player.user.first_name }}</a></td>
                        {% if  player.main == 'MA' %}
                        <td><img src="{% static 'ratesmash/images/MA.png' %}" alt="{{ player.main }}"/></td>
                        {% elif  player.main == 'DK' %}
                        <td><img src="{% static 'ratesmash/images/DK.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'LI' %}
                        <td><img src="{% static 'ratesmash/images/LI.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'SA' %}
                        <td><img src="{% static 'ratesmash/images/SA.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'YO' %}
                        <td><img src="{% static 'ratesmash/images/YO.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'KI' %}
                        <td><img src="{% static 'ratesmash/images/KI.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'FO' %}
                        <td><img src="{% static 'ratesmash/images/FO.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'PI' %}
                        <td><img src="{% static 'ratesmash/images/PI.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'LU' %}
                        <td><img src="{% static 'ratesmash/images/LU.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'NE' %}
                        <td><img src="{% static 'ratesmash/images/NE.png' %}" alt="{{ player.main }}"/></td>
                        {% elif player.main == 'CF' %}
                        <td><img src="{% static 'ratesmash/images/CF.png' %}" alt="{{ player.main }}"/></td>
                        {% else %}
                        <td><img src="{% static 'ratesmash/images/PU.png' %}" alt="{{ player.main }}"/></td>     
                        {% endif %}
                        <td>{{ player.rate }}</td>
                    </tr>
                {% endfor %}
                </table>
            </div>
            
        </div>
        
        <p><a href="#">一番上へ</a></p>
        <p><a href="{% url 'ratesmash:index' %}">Homeへ</a></p>
        
        <hr>
        
        <footer>
            <p>Respected 大乱闘スマッシュブラザーズ<br>Copyright © 2018 beginnerpython rights reserved.</p>
        </footer>
    </div>
</body>
</html>

ratesmash/templates/ratesmash/room_detail.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" type="text/css" 
    href="{% static 'ratesmash/style.css' %}" />
</head>
<body>
    <header>
        <h1><a href="{% url 'ratesmash:index' %}">{{ title }}</a></h1>
        <p>
        <strong>beginner python</strong> による勉強用サイトです！<br>
        初めての方はhow to playを一読してからご利用ください！
        </p>
        <h2>{{ subtitle }}</h2>
    </header>
    
    <hr>
    
    <nav class="menu">
        <ul class="menu-bar">
            <li class="menu-item"><a href="{% url 'ratesmash:create_room' %}">部屋をつくる</a></li>
            <li class="menu-item"><a href="{% url 'ratesmash:all_players' %}">プレイヤー一覧</a></li>
            <li class="menu-item"><a href="{% url 'ratesmash:ranking' %}">ランキング</a></li>
            <li class="menu-item"><a href="{% url 'ratesmash:howtoplay' %}">ヘルプ</a></li>
        </ul>
    </nav>
    
    <hr>
    
    {% if room.state == 'w' %}
    <p>game information</p>
    <table class="room-detail">
        <tr>
            <th>集合サーバー</th>
            <th>counter foctor</th>
            <th>コメント</th>
        </tr>
        <tr>
            <td>{{ room.server }}</td>
            <td>{{ room.cf }}</td>
            <td>{{ room.comment }}</td>
        </tr>
    </table>
    {% endif %}
    
    {% if room.state == 'w' %}
    {% if room.mode == False %}
    <table class="room-owner">
        <tr>
            <th>部屋主</th>
            <td>{{ room.owner.user.first_name }}</td>
        </tr>
        <tr>
            <th>キャラクター</th>
            {% if  room.owner.main == 'MA' %}
            <td><img src="{% static 'ratesmash/images/MA.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif  room.owner.main == 'DK' %}
            <td><img src="{% static 'ratesmash/images/DK.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'LI' %}
            <td><img src="{% static 'ratesmash/images/LI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'SA' %}
            <td><img src="{% static 'ratesmash/images/SA.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'YO' %}
            <td><img src="{% static 'ratesmash/images/YO.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'KI' %}
            <td><img src="{% static 'ratesmash/images/KI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'FO' %}
            <td><img src="{% static 'ratesmash/images/FO.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'PI' %}
            <td><img src="{% static 'ratesmash/images/PI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'LU' %}
            <td><img src="{% static 'ratesmash/images/LU.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'NE' %}
            <td><img src="{% static 'ratesmash/images/NE.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'CF' %}
            <td><img src="{% static 'ratesmash/images/CF.png' %}" alt="{{ room.owner.main }}"/></td>
            {% else %}
            <td><img src="{% static 'ratesmash/images/PU.png' %}" alt="{{ room.owner.main }}"/></td>     
            {% endif %}
        </tr>
        <tr>
            <th>レート</th>
            <td>{{ room.rate_o }}</td>
        </tr>
        <tr>
            <th>対戦結果</th>
            <td class="{{ resulto }}">
            {% if resulto == True %}WIN{% endif %}
            {% if resulto == False %}LOSS{% endif %}
            </td>
        </tr>
        {% if room.owner == player %}
        <tr>
            <td><a href="{% url 'ratesmash:delete_room' room.id %}"><input type="submit" value="delete" class="button"><a/></td>
        </tr>
        {% endif %}
    </table>
    {% else %}
    <table class="room-owner">
        <tr>
            <th>部屋主</th>
            <td>?</td>
        </tr>
        <tr>
            <th>キャラクター</th>
            <td><img src="{% static 'ratesmash/images/SF.png' %}" alt="?" /></td>
        </tr>
        <tr>
            <th>レート</th>
            <td>?</td>
        </tr>
        <tr>
            <th>対戦結果</th>
            <td class="{{ resulto }}">
            {% if resulto == True %}WIN{% endif %}
            {% if resulto == False %}LOSS{% endif %}
            </td>
        </tr>
        {% if room.owner == player %}
        <tr>
            <td><a href="{% url 'ratesmash:delete_room' room.id %}"><input type="submit" value="delete" class="button"><a/></td>
        </tr>
        {% endif %}
    </table>
    {% endif %}
    {% endif %}
    
    {% if room.state != 'w' %}
    <table class="room-owner">
        <tr>
            <th>部屋主</th>
            <td>{{ room.owner.user.first_name }}</td>
        </tr>
        <tr>
            <th>キャラクター</th>
            {% if  room.owner.main == 'MA' %}
            <td><img src="{% static 'ratesmash/images/MA.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif  room.owner.main == 'DK' %}
            <td><img src="{% static 'ratesmash/images/DK.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'LI' %}
            <td><img src="{% static 'ratesmash/images/LI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'SA' %}
            <td><img src="{% static 'ratesmash/images/SA.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'YO' %}
            <td><img src="{% static 'ratesmash/images/YO.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'KI' %}
            <td><img src="{% static 'ratesmash/images/KI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'FO' %}
            <td><img src="{% static 'ratesmash/images/FO.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'PI' %}
            <td><img src="{% static 'ratesmash/images/PI.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'LU' %}
            <td><img src="{% static 'ratesmash/images/LU.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'NE' %}
            <td><img src="{% static 'ratesmash/images/NE.png' %}" alt="{{ room.owner.main }}"/></td>
            {% elif room.owner.main == 'CF' %}
            <td><img src="{% static 'ratesmash/images/CF.png' %}" alt="{{ room.owner.main }}"/></td>
            {% else %}
            <td><img src="{% static 'ratesmash/images/PU.png' %}" alt="{{ room.owner.main }}"/></td>     
            {% endif %}
        </tr>
        <tr>
            <th>レート</th>
            <td>{{ room.rate_o }}</td>
        </tr>
        <tr>
            <th>対戦結果</th>
            <td class="{{ resulto }}">
            {% if resulto == True %}WIN{% endif %}
            {% if resulto == False %}LOSS{% endif %}
            </td>
        </tr>
        {% if room.owner == player %}
        <tr>
            <td><a href="{% url 'ratesmash:delete_room' room.id %}"><input type="submit" value="delete" class="button"><a/></td>
        </tr>
        {% endif %}
    </table>
    {% endif%}
    
    <p>vs</p>
    
    <table class="room-participant">
        <tr>
            <th>対戦相手</th>
            <td>{{ room.participant.user.first_name }}</td>
        </tr>
        <tr>
            <th>キャラクター</th>
            {% if  room.participant.main == 'MA' %}
            <td><img src="{% static 'ratesmash/images/MA.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif  room.participant.main == 'DK' %}
            <td><img src="{% static 'ratesmash/images/DK.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'LI' %}
            <td><img src="{% static 'ratesmash/images/LI.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'SA' %}
            <td><img src="{% static 'ratesmash/images/SA.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'YO' %}
            <td><img src="{% static 'ratesmash/images/YO.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'KI' %}
            <td><img src="{% static 'ratesmash/images/KI.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'FO' %}
            <td><img src="{% static 'ratesmash/images/FO.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'PI' %}
            <td><img src="{% static 'ratesmash/images/PI.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'LU' %}
            <td><img src="{% static 'ratesmash/images/LU.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'NE' %}
            <td><img src="{% static 'ratesmash/images/NE.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'CF' %}
            <td><img src="{% static 'ratesmash/images/CF.png' %}" alt="{{ room.participant.main }}"/></td>
            {% elif room.participant.main == 'PU'  %}
            <td><img src="{% static 'ratesmash/images/PU.png' %}" alt="{{ room.participant.main }}"/></td>
            {% else %}
            <td></td>   
            {% endif %}
        </tr>
        <tr>
            <th>レート</th>
            <td>{{ room.rate_p }}</td>
        </tr>
        <tr>
            <th>対戦結果</th>
            <td class="{{ resultp }}">
            {% if resultp == True %}WIN{% endif %}
            {% if resultp == False %}LOSS{% endif %}
            </td>
        </tr>
        {% if room.state == 'w' %}
        <tr>
            <td>
                <a href="{% url 'ratesmash:join_room' room.id %}"><input type="submit" value="この部屋に参加" class="button"><a/>
            </td>
        </tr>
        {% endif %}
    </table>
    
    <p><a href="#">一番上へ</a></p>
    <p><a href="{% url 'ratesmash:index' %}">Homeへ</a></p>
    
    <hr>
    
    <footer>
        <p>Respected 大乱闘スマッシュブラザーズ<br>Copyright © 2018 beginnerpython rights reserved.</p>
    </footer>
    
</body>
</html>